FROM node:22-alpine
WORKDIR /app

COPY package.json package-lock.json ./
COPY packages ./packages
COPY apps ./apps

RUN npm ci

WORKDIR /app/packages/shared
RUN npm run build

WORKDIR /app/apps/api
RUN npx prisma generate && npm run build

EXPOSE 3001
CMD ["node", "dist/main.js"]
