export const USERBOT_POLL_INTERVAL_MS = 2000;
export const USERBOT_POLL_FETCH_LIMIT = 20;
export const USERBOT_PROCESSING_CONCURRENCY = 4;
export const USERBOT_MAX_QUEUE_DEFAULT = 300;
export const USERBOT_INLINE_TEXT_MAX_CHARS = 4_000;
export const USERBOT_MAX_MESSAGE_AGE_MINUTES_DEFAULT = 10;
export const USERBOT_MIN_BALANCE_USD_DEFAULT = 3;
export const USERBOT_BALANCE_CHECK_CACHE_MS = 30_000;
export const USERBOT_FILTER_MATCH_THRESHOLD = 0.34;
export const CLOSE_REOPEN_COOLDOWN_MS = 30_000;
export const CRITICAL_NOTIFY_URL = 'https://qnotify.up.railway.app';
export const OPENROUTER_BALANCE_LOW_THRESHOLD_USD = 2;
export const OPENROUTER_BALANCE_NOTIFY_COOLDOWN_MS = 30 * 60_000;
/** Опрос Telegram после ошибки уровней (validateSignalLevels). */
export const USERBOT_SIGNAL_LEVELS_EDIT_WATCH_POLL_MS = 25_000;
export const USERBOT_SIGNAL_LEVELS_EDIT_WATCH_TTL_MS = 90 * 60_000;
