export const CABINET_SCOPED_SETTING_KEYS = [
  'BYBIT_TESTNET',
  'BYBIT_API_KEY_MAINNET',
  'BYBIT_API_SECRET_MAINNET',
  'BYBIT_API_KEY_TESTNET',
  'BYBIT_API_SECRET_TESTNET',
  'DEFAULT_ORDER_USD',
  'MIN_CAPITAL_AMOUNT',
  'BUMP_TO_MIN_EXCHANGE_LOT',
  'DEFAULT_LEVERAGE_ENABLED',
  'DEFAULT_LEVERAGE',
  'FORCED_LEVERAGE',
  'LEVERAGE_RANGE_MODE',
  'MIN_ALLOWED_LEVERAGE',
  'MAX_ALLOWED_LEVERAGE',
  'SIGNAL_SOURCE',
  'TELEGRAM_WHITELIST',
  'TELEGRAM_BOT_TOKEN',
  'TELEGRAM_NOTIFY_API_TRADE_CANCELLED',
  'TELEGRAM_NOTIFY_TRADE_EVENTS',
  'TELEGRAM_NOTIFY_TRADE_EVENT_TYPES',
  'SOURCE_MARTINGALE_DEFAULT_MULTIPLIER',
  'SOURCE_MARTINGALE_MULTIPLIERS',
  'SOURCE_LIST',
  'SOURCE_EXCLUDE_LIST',
  'TP_SL_STEP_START',
  'TP_SL_STEP_RANGE',
  'SOURCE_TP_SL_STEP_START',
  'SOURCE_TP_SL_STEP_RANGE',
] as const;

export const CABINET_SCOPED_SETTING_KEY_SET = new Set<string>(
  CABINET_SCOPED_SETTING_KEYS,
);

export type CabinetScopedSettingKey = (typeof CABINET_SCOPED_SETTING_KEYS)[number];

