export const CABINET_TRADING_OVERVIEW_KEYS = [
  'BYBIT_TESTNET',
  'MIN_CAPITAL_AMOUNT',
  'DEFAULT_ORDER_USD',
  'BUMP_TO_MIN_EXCHANGE_LOT',
  'DEFAULT_LEVERAGE_ENABLED',
  'DEFAULT_LEVERAGE',
  'FORCED_LEVERAGE',
  'LEVERAGE_RANGE_MODE',
  'MIN_ALLOWED_LEVERAGE',
  'MAX_ALLOWED_LEVERAGE',
  'SOURCE_MARTINGALE_DEFAULT_MULTIPLIER',
  'BYBIT_ACCOUNT_MAX_CONCURRENCY',
  'TP_SL_STEP_START',
  'TP_SL_STEP_RANGE',
] as const;

export const CABINET_TELEGRAM_OVERVIEW_KEYS = [
  'TELEGRAM_BOT_TOKEN',
  'SIGNAL_SOURCE',
  'TELEGRAM_WHITELIST',
  'TELEGRAM_NOTIFY_API_TRADE_CANCELLED',
  'TELEGRAM_NOTIFY_TRADE_EVENTS',
  'TELEGRAM_NOTIFY_TRADE_EVENT_TYPES',
] as const;

export const CABINET_EXCLUDED_SOURCES_KEY = 'SOURCE_EXCLUDE_LIST';
