import { NAV_MENU_HIDDEN_SETTING_KEY } from '@repo/shared';

export const DASHBOARD_TODOS_MAX_ITEMS = 200;
export const DASHBOARD_TODOS_MAX_ID_LEN = 80;
export const DASHBOARD_TODOS_MAX_TEXT_LEN = 4000;

export const ENV_FALLBACK: Record<string, string> = {
  APPLOG_ENABLED: 'true',
  DEFAULT_ORDER_USD: '10',
  BUMP_TO_MIN_EXCHANGE_LOT: 'false',
  APPLOG_LOG_NOISY_EVENTS: 'false',
  TP_SL_STEP_RANGE: '',
};

export const GLOBAL_SHARED_SETTING_KEYS = new Set<string>([
  NAV_MENU_HIDDEN_SETTING_KEY,
  'OPENROUTER_API_KEY',
  'OPENROUTER_MODEL_DEFAULT',
  'OPENROUTER_MODEL_TEXT',
  'OPENROUTER_MODEL_AI_ADVISOR',
  'OPENROUTER_MODEL_TEXT_FALLBACK_1',
  'OPENROUTER_MODEL_IMAGE',
  'OPENROUTER_MODEL_IMAGE_FALLBACK_1',
  'OPENROUTER_MODEL_AUDIO',
  'OPENROUTER_MODEL_AUDIO_FALLBACK_1',
  'OPENROUTER_MODEL_HISTORY',
  'DIAGNOSTIC_BATCH_SIZE',
  'DIAGNOSTIC_MAX_LOG_LINES',
  'APPLOG_ENABLED',
  'APPLOG_LOG_NOISY_EVENTS',
  'OPENROUTER_DIAGNOSTIC_MODELS',
  'MIN_CAPITAL_AMOUNT',
  'DEFAULT_ORDER_USD',
  'BUMP_TO_MIN_EXCHANGE_LOT',
  'DEFAULT_LEVERAGE_ENABLED',
  'DEFAULT_LEVERAGE',
  'FORCED_LEVERAGE',
  'LEVERAGE_RANGE_MODE',
  'MIN_ALLOWED_LEVERAGE',
  'MAX_ALLOWED_LEVERAGE',
  'SOURCE_MARTINGALE_DEFAULT_MULTIPLIER',
  'POLLING_INTERVAL_MS',
  'TP_SL_STEP_START',
  'TP_SL_STEP_RANGE',
]);

export const ADMIN_ONLY_GLOBAL_KEYS = new Set<string>(GLOBAL_SHARED_SETTING_KEYS);
